IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.0001
BETA_1: 0.9
BETA_2: 0.999
DECAY: 0.0001

LIST_FOLDER_NAME: ["train", "dev", "test"]
LIST_LABEL_NAME : ["ASC_H", "ASC_US", "HSIL", "LSIL", "SCC"]

